Repository libraryofcode/dis.ts, pull requests merged in 2020-12, with the labels that each got.

#9 WebSocket 2
  package-lock.json
  package.json
  src/gateway/WebSocket.ts
  src/gateway/constants.ts
Labels: c: ws, semver: feat, t: addition

#11 Updated User Flags
  src/util/Constants.ts
Labels: prio: low, t: addition

#13 WebSocket resume
  README.md
  src/gateway/WebSocket.ts
  src/gateway/constants.ts
Labels: repo: gw, semver: feat, t: addition
